### ISSUE TITLE
NoMethodError in UploadsController#create - undefined method `permit' for nil:NilClass

### ISSUE THREAD

**Issue by gregblass** [5minpause/multiple-file-upload#3] opened 2014-02-25 22:33 UTC
Thanks for posting this code and tutorial. It looks like a great start to what I need to do.

I downloaded the source code, ran bundle install (using RVM), uncommented database.yml and created a database table to get this running. However, when I try to upload a file, I'm running into this error:

NoMethodError in UploadsController#create - undefined method `permit' for nil:NilClass
Extracted source (around line #62):

params[:upload].permit(:uploaded_file)

Any idea as to what could be causing this?

**Comment by 5minpause** [comment] 2014-02-26 07:20
Thank you. 
That's difficult to say without seeing more of the error message. Could you post the whole log from your create action, including the parameters.

Some random questions regarding this:
- Which version of rails are you using?
- If rails 4, are you using strong_parameters gem?
- what do your form and controller look like?

**Comment by gregblass** [comment] 2014-02-26 12:43
- I'm using the version of rails specified in the gem file.
- I'm not using any special gems (I just downloaded the code and ran it) - I was under the assumption that rails 4 has strong parameters enabled by default.
- I did not modify the code that is in this project. They are exactly as they are in the repository.

**Comment by 5minpause** [comment] 2014-02-26 13:07
Okay.

I just did a clean checkout of the project and uploaded three files, without problems.
This is what my post action in the log looks like: (with line breaks added for readability)

```
Started POST "/uploads" for 127.0.0.1 at 2014-02-26 14:04:44 +0100
Processing by UploadsController#create as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"aNKRVhba+4K8pHONjWzkdf987JlqdRsxpswAFsxl4j8=",
"upload"=>{"uploaded_file"=>#<ActionDispatch::Http::UploadedFile:0x007fc9102b10e8 @tempfile=#<Tempfile:/var/folders/w7/6psdv1q12yb16t6dp57v2jg40000gn/T/RackMultipart20140226-4587-14ya24f>, 
@original_filename="Screen Shot 2013-11-25 at 10.19.58.png", 
@content_type="image/png", 
@headers="Content-Disposition: form-data; name=\"upload[uploaded_file]\"; filename=\"Screen Shot 2013-11-25 at 10.19.58.png\"\r\nContent-Type: image/png\r\n">}}
```

**Comment by 5minpause** [comment] 2014-02-28 13:49
Any more comments or questions from you?

**Comment by Phitherek** [comment] 2014-04-08 07:56
Hello,
Same error for me. Here is the server log:

```
Started POST "/uploads" for 127.0.0.1 at 2014-04-08 09:51:41 +0200
Processing by UploadsController#create as JS
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"IyLCzvbxfP1nURxNr5lOJGs0KI6Gv/CDPdghdF4oDtk=", "upload"=>{"uploaded_file"=>#<ActionDispatch::Http::UploadedFile:0x0000000146d8a8 @tempfile=#<Tempfile:/tmp/RackMultipart20140408-12454-x4bgbh>, @original_filename="PHI_0084_s.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"upload[uploaded_file]\"; filename=\"PHI_0084_s.jpg\"\r\nContent-Type: image/jpeg\r\n">}}
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/PHI_0084_s20140408-12454-1igqztn.jpg[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn.jpg[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn.jpg[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn.jpg[0]'
Command :: convert '/tmp/PHI_0084_s20140408-12454-1igqztn.jpg[0]' -auto-orient -resize "4000x4000>" '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf'
Command :: file -b --mime '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: convert '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]' -auto-orient -resize "1500x1500>" '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-3vnmh3'
Command :: file -b --mime '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-3vnmh3'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: convert '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]' -auto-orient -resize "300x300>" '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-wgnq07'
Command :: file -b --mime '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-wgnq07'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: convert '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]' -auto-orient -resize "200x200>" '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-zjsdnv'
Command :: file -b --mime '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-zjsdnv'
Command :: identify -format '%wx%h,%[exif:orientation]' '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: identify -format %m '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]'
Command :: convert '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x[0]' -auto-orient -resize "100x100>" '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-ch2bf7'
Command :: file -b --mime '/tmp/PHI_0084_s20140408-12454-1igqztn20140408-12454-gfe2nf20140408-12454-15mk78x20140408-12454-ch2bf7'
   (0.4ms)  begin transaction
Binary data inserted for `string` type on column `uploaded_file_content_type`
  SQL (1.5ms)  INSERT INTO "uploads" ("created_at", "updated_at", "uploaded_file_content_type", "uploaded_file_file_name", "uploaded_file_file_size", "uploaded_file_updated_at") VALUES (?, ?, ?, ?, ?, ?)  [["created_at", Tue, 08 Apr 2014 07:51:49 UTC +00:00], ["updated_at", Tue, 08 Apr 2014 07:51:49 UTC +00:00], ["uploaded_file_content_type", "image/jpeg"], ["uploaded_file_file_name", "PHI_0084_s.jpg"], ["uploaded_file_file_size", 858507], ["uploaded_file_updated_at", Tue, 08 Apr 2014 07:51:41 UTC +00:00]]
   (157.2ms)  commit transaction
  Rendered uploads/_upload.html.erb (2.1ms)
  Rendered uploads/create.js.erb (8.3ms)
Completed 200 OK in 8875ms (Views: 21.8ms | ActiveRecord: 159.1ms)


Started POST "/uploads" for 127.0.0.1 at 2014-04-08 09:51:50 +0200
Processing by UploadsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"IyLCzvbxfP1nURxNr5lOJGs0KI6Gv/CDPdghdF4oDtk=", "commit"=>"Create Upload"}
Completed 500 Internal Server Error in 3ms

NoMethodError (undefined method `permit' for nil:NilClass):
  app/controllers/uploads_controller.rb:62:in `upload_params'
  app/controllers/uploads_controller.rb:27:in `create'


  Rendered /home/phitherek/.rvm/gems/ruby-2.0.0-p353@multiple-fupload/gems/actionpack-4.0.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.3ms)
  Rendered /home/phitherek/.rvm/gems/ruby-2.0.0-p353@multiple-fupload/gems/actionpack-4.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.erb (3.9ms)
  Rendered /home/phitherek/.rvm/gems/ruby-2.0.0-p353@multiple-fupload/gems/actionpack-4.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (3.4ms)
  Rendered /home/phitherek/.rvm/gems/ruby-2.0.0-p353@multiple-fupload/gems/actionpack-4.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (40.6ms)
```

It happens after I click the "Create upload" button.

**Comment by 5minpause** [comment] 2014-04-08 10:14
Alright, thanks for posting your log. The problem is that the request is submitted or processed twice. The first time it's a JS request: 

```
Started POST "/uploads" for 127.0.0.1 at 2014-04-08 09:51:41 +0200
Processing by UploadsController#create as JS
```

The second time it's a HTML request: 

```
Started POST "/uploads" for 127.0.0.1 at 2014-04-08 09:51:50 +0200
Processing by UploadsController#create as HTML
```

The HTML request is missing the upload params. That's okay, because it shouldn't be there in the first place. But it leads to your `no method error` because the `params[:upload]` is `nil`:

```
NoMethodError (undefined method `permit' for nil:NilClass):
```

Did you alter any code from the repository? I honestly don't know right now why you have two requests. But I guess we can figure it out.

**Comment by Phitherek** [comment] 2014-04-08 11:09
No, I did not alter anything in the code except of database configuration. Also, there was not two, but three requests - two of them were caused by the file upload and the last one - by the button click. I did not post them because the log would be too long and the requests were really similar.

**Comment by Phitherek** [comment] 2014-04-08 11:34
Ok, so the problem seems to be either the behaviour of the upload form or the uploads#create action. The plugin starts upload just after the files are submitted on the file selection field. It makes the call to create as JS for every file, which works fine. But the form itself and the submit button ("Create upload") also go to the create (POST /uploads) action but as HTML, but this time without any upload parameters and it crashes the action. I would suggest at least two solutions:
1. Get rid of the submit button, as the plugin clearly does not use it in any way and the uploads are created automatically.
2. In create action respond to JS with upload creation and to HTML with redirection instead, like this:

```
 # POST /uploads
  # POST /uploads.json
  def create
    respond_to do |format|
      format.js do
        @upload = Upload.create(upload_params)
      end
      format.html do
        redirect_to uploads_path
      end
    end
  end
```

Works perfectly for me.

**Comment by 5minpause** [comment] 2014-04-08 11:41
What browser do you use for testing?

I guess we should put a `event.preventDefault()` in there to suppress the default submitting (http://api.jquery.com/event.preventDefault/)

**Comment by Phitherek** [comment] 2014-04-08 11:49
I am testing this on Chromium 33.0.1750.117 (252094)

When it comes to auto-submitting, I suppose that jQuery File Upload does this by default. There is a setup on this wiki page to change this: https://github.com/blueimp/jQuery-File-Upload/wiki/Basic-plugin

**Comment by 5minpause** [comment] 2014-04-08 12:01
Curious why it doesn't work for you by default?! A clean checkout works flawlessly for me. Interesting change you made there. Unfortunately I cannot work on this right now.

**Comment by Phitherek** [comment] 2014-04-08 12:06
Ok, I' ve got this now :).
This is the modification of uploads.js.coffee, which makes uploads start only when you click the "Create Upload" button and then resets the upload form, so you can upload even more files. And this is my third solution.

```
# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

jQuery ->
  $('#upload_uploaded_file').attr('name','upload[uploaded_file]')
  $('#new_upload').fileupload
    dataType: 'script'
    add: (e, data) ->
      types = /(\.|\/)(gif|jpe?g|png|mov|mpeg|mpeg4|avi)$/i
      file = data.files[0]
      if types.test(file.type) || types.test(file.name)
        data.context = $(tmpl("template-upload", file))
        $('#new_upload').append(data.context)
        $('.actions input[type="submit"]').click (e) ->
          data.submit()
          e.preventDefault()           
      else
        alert("#{file.name} is not a gif, jpg or png image file")
    progress: (e, data) ->
      if data.context
        progress = parseInt(data.loaded / data.total * 100, 10)
        data.context.find('.bar').css('width', progress + '%')
    done: (e, data) ->
      $('.actions input[type="submit"]').off('click')
```

Hopefully you will find some time to look at it later.

**Comment by Phitherek** [comment] 2014-04-08 19:05
Thank you for the merge. I also like this solution because it shows how to change the default behaviour of jQuery FileUpload and will definitely be useful to others. I am curious why you could not reproduce the bug on your side but well, if it works now for you and me then possibly it will work now for many more people ;).

I think you can safely close this now.

**Closed as completed** 2014-09-06 11:03 UTC
